name: My First workflow

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: list file
        run: ls

  say-bye:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: |
          echo "Bye!"
          echo "Sajal Gupta pull request"
