name: My First workflow

on:
  push:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: |
          echo "Sajal Gupta"

  say-bye:
    needs: say-hello
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: |
          echo "Bye!"
          echo "Sajal Gupta pull request"